name: Auto-merge Beta

on:
  pull_request:
    branches:
      - master
    paths:
      - 'drive-beta.rb'

permissions:
  pull-requests: write
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: diff
        # This step will also throw an error if more than 1 file is changed.
        if: ${{ startsWith(github.head_ref,	'release/') }}
        run: echo "files=$(gh pr diff --name-only $PR_URL)" >> $GITHUB_OUTPUT
      - if: ${{ steps.diff.outputs.files == 'drive-beta.rb' }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge -d -s "$PR_URL"
